### ISSUE TITLE
The specified Atlas version does not exist or is no longer supported.

### ISSUE THREAD

**Issue by till** [ariga/setup-atlas#5]
I had locked atlas cli to a specific version and it stopped working today:

> The specified Atlas version does not exist or is no longer supported.

```yaml
      - uses: ariga/setup-atlas@v0
        with:
          version: v0.18.0
```

Is there a simple way to introduce this updates with dependabot instead of making the workflow fail? Like, I am happy to update, but I don't want new releases that may have BC breaks in the middle of what I want I am working on. Other GitHub Actions would typically update `v0` and that would allow me to use dependabot for updates.

What do you suggest?
